kind: Service
apiVersion: v1
metadata:
  name: helidonmp
  labels:
    app: helidonmp
spec:
  type: NodePort
  selector:
    app: helidonmp
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: helidonmp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helidonmp
  template:
    metadata:
      labels:
        app: helidonmp
        version: v1
    spec:
      containers:
      - name: helidonmp
        image: helidonmp
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
